# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d48fcb930af413f7abb6e621363aaa36ae8df7c861e4228a746a9a5c4dbb4d93ca466ba7240bf07a397d012192838cb211b4689d9b787b627f7ac474f217ec48

test:
  secret_key_base: 106254a6d92da901b6af764c19bca280c0340e144cb3a8d62fc81b41d6dfd10556e5280a9a0a22ad1c8f7af8b27eb0b642678a790179c6d698c68b1319b974bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
